/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaithProjectsRouteImport } from './routes/faith-projects'
import { Route as CohortsRouteImport } from './routes/cohorts'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as ParticipantsIndexRouteImport } from './routes/participants.index'
import { Route as SupportScheduleRouteImport } from './routes/support.schedule'
import { Route as SupportResourcesRouteImport } from './routes/support.resources'
import { Route as SupportProfileRouteImport } from './routes/support.profile'
import { Route as SupportGuideRouteImport } from './routes/support.guide'
import { Route as SupportAttendanceRouteImport } from './routes/support.attendance'
import { Route as ParticipantsIdRouteImport } from './routes/participants.$id'
import { Route as SupportParticipantsIndexRouteImport } from './routes/support.participants.index'
import { Route as SupportParticipantsIdRouteImport } from './routes/support.participants.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaithProjectsRoute = FaithProjectsRouteImport.update({
  id: '/faith-projects',
  path: '/faith-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const CohortsRoute = CohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportRoute,
} as any)
const ParticipantsIndexRoute = ParticipantsIndexRouteImport.update({
  id: '/participants/',
  path: '/participants/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportScheduleRoute = SupportScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => SupportRoute,
} as any)
const SupportResourcesRoute = SupportResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => SupportRoute,
} as any)
const SupportProfileRoute = SupportProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SupportRoute,
} as any)
const SupportGuideRoute = SupportGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => SupportRoute,
} as any)
const SupportAttendanceRoute = SupportAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => SupportRoute,
} as any)
const ParticipantsIdRoute = ParticipantsIdRouteImport.update({
  id: '/participants/$id',
  path: '/participants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportParticipantsIndexRoute =
  SupportParticipantsIndexRouteImport.update({
    id: '/participants/',
    path: '/participants/',
    getParentRoute: () => SupportRoute,
  } as any)
const SupportParticipantsIdRoute = SupportParticipantsIdRouteImport.update({
  id: '/participants/$id',
  path: '/participants/$id',
  getParentRoute: () => SupportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/approvals': typeof ApprovalsRoute
  '/attendance': typeof AttendanceRoute
  '/cohorts': typeof CohortsRoute
  '/faith-projects': typeof FaithProjectsRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRouteWithChildren
  '/users': typeof UsersRoute
  '/participants/$id': typeof ParticipantsIdRoute
  '/support/attendance': typeof SupportAttendanceRoute
  '/support/guide': typeof SupportGuideRoute
  '/support/profile': typeof SupportProfileRoute
  '/support/resources': typeof SupportResourcesRoute
  '/support/schedule': typeof SupportScheduleRoute
  '/participants/': typeof ParticipantsIndexRoute
  '/support/': typeof SupportIndexRoute
  '/support/participants/$id': typeof SupportParticipantsIdRoute
  '/support/participants/': typeof SupportParticipantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/approvals': typeof ApprovalsRoute
  '/attendance': typeof AttendanceRoute
  '/cohorts': typeof CohortsRoute
  '/faith-projects': typeof FaithProjectsRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/participants/$id': typeof ParticipantsIdRoute
  '/support/attendance': typeof SupportAttendanceRoute
  '/support/guide': typeof SupportGuideRoute
  '/support/profile': typeof SupportProfileRoute
  '/support/resources': typeof SupportResourcesRoute
  '/support/schedule': typeof SupportScheduleRoute
  '/participants': typeof ParticipantsIndexRoute
  '/support': typeof SupportIndexRoute
  '/support/participants/$id': typeof SupportParticipantsIdRoute
  '/support/participants': typeof SupportParticipantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/approvals': typeof ApprovalsRoute
  '/attendance': typeof AttendanceRoute
  '/cohorts': typeof CohortsRoute
  '/faith-projects': typeof FaithProjectsRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRouteWithChildren
  '/users': typeof UsersRoute
  '/participants/$id': typeof ParticipantsIdRoute
  '/support/attendance': typeof SupportAttendanceRoute
  '/support/guide': typeof SupportGuideRoute
  '/support/profile': typeof SupportProfileRoute
  '/support/resources': typeof SupportResourcesRoute
  '/support/schedule': typeof SupportScheduleRoute
  '/participants/': typeof ParticipantsIndexRoute
  '/support/': typeof SupportIndexRoute
  '/support/participants/$id': typeof SupportParticipantsIdRoute
  '/support/participants/': typeof SupportParticipantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/approvals'
    | '/attendance'
    | '/cohorts'
    | '/faith-projects'
    | '/login'
    | '/resources'
    | '/schedule'
    | '/settings'
    | '/support'
    | '/users'
    | '/participants/$id'
    | '/support/attendance'
    | '/support/guide'
    | '/support/profile'
    | '/support/resources'
    | '/support/schedule'
    | '/participants/'
    | '/support/'
    | '/support/participants/$id'
    | '/support/participants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/approvals'
    | '/attendance'
    | '/cohorts'
    | '/faith-projects'
    | '/login'
    | '/resources'
    | '/schedule'
    | '/settings'
    | '/users'
    | '/participants/$id'
    | '/support/attendance'
    | '/support/guide'
    | '/support/profile'
    | '/support/resources'
    | '/support/schedule'
    | '/participants'
    | '/support'
    | '/support/participants/$id'
    | '/support/participants'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/approvals'
    | '/attendance'
    | '/cohorts'
    | '/faith-projects'
    | '/login'
    | '/resources'
    | '/schedule'
    | '/settings'
    | '/support'
    | '/users'
    | '/participants/$id'
    | '/support/attendance'
    | '/support/guide'
    | '/support/profile'
    | '/support/resources'
    | '/support/schedule'
    | '/participants/'
    | '/support/'
    | '/support/participants/$id'
    | '/support/participants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AttendanceRoute: typeof AttendanceRoute
  CohortsRoute: typeof CohortsRoute
  FaithProjectsRoute: typeof FaithProjectsRoute
  LoginRoute: typeof LoginRoute
  ResourcesRoute: typeof ResourcesRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRouteWithChildren
  UsersRoute: typeof UsersRoute
  ParticipantsIdRoute: typeof ParticipantsIdRoute
  ParticipantsIndexRoute: typeof ParticipantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faith-projects': {
      id: '/faith-projects'
      path: '/faith-projects'
      fullPath: '/faith-projects'
      preLoaderRoute: typeof FaithProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohorts': {
      id: '/cohorts'
      path: '/cohorts'
      fullPath: '/cohorts'
      preLoaderRoute: typeof CohortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/participants/': {
      id: '/participants/'
      path: '/participants'
      fullPath: '/participants/'
      preLoaderRoute: typeof ParticipantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/schedule': {
      id: '/support/schedule'
      path: '/schedule'
      fullPath: '/support/schedule'
      preLoaderRoute: typeof SupportScheduleRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/resources': {
      id: '/support/resources'
      path: '/resources'
      fullPath: '/support/resources'
      preLoaderRoute: typeof SupportResourcesRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/profile': {
      id: '/support/profile'
      path: '/profile'
      fullPath: '/support/profile'
      preLoaderRoute: typeof SupportProfileRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/guide': {
      id: '/support/guide'
      path: '/guide'
      fullPath: '/support/guide'
      preLoaderRoute: typeof SupportGuideRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/attendance': {
      id: '/support/attendance'
      path: '/attendance'
      fullPath: '/support/attendance'
      preLoaderRoute: typeof SupportAttendanceRouteImport
      parentRoute: typeof SupportRoute
    }
    '/participants/$id': {
      id: '/participants/$id'
      path: '/participants/$id'
      fullPath: '/participants/$id'
      preLoaderRoute: typeof ParticipantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/participants/': {
      id: '/support/participants/'
      path: '/participants'
      fullPath: '/support/participants/'
      preLoaderRoute: typeof SupportParticipantsIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/participants/$id': {
      id: '/support/participants/$id'
      path: '/participants/$id'
      fullPath: '/support/participants/$id'
      preLoaderRoute: typeof SupportParticipantsIdRouteImport
      parentRoute: typeof SupportRoute
    }
  }
}

interface SupportRouteChildren {
  SupportAttendanceRoute: typeof SupportAttendanceRoute
  SupportGuideRoute: typeof SupportGuideRoute
  SupportProfileRoute: typeof SupportProfileRoute
  SupportResourcesRoute: typeof SupportResourcesRoute
  SupportScheduleRoute: typeof SupportScheduleRoute
  SupportIndexRoute: typeof SupportIndexRoute
  SupportParticipantsIdRoute: typeof SupportParticipantsIdRoute
  SupportParticipantsIndexRoute: typeof SupportParticipantsIndexRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportAttendanceRoute: SupportAttendanceRoute,
  SupportGuideRoute: SupportGuideRoute,
  SupportProfileRoute: SupportProfileRoute,
  SupportResourcesRoute: SupportResourcesRoute,
  SupportScheduleRoute: SupportScheduleRoute,
  SupportIndexRoute: SupportIndexRoute,
  SupportParticipantsIdRoute: SupportParticipantsIdRoute,
  SupportParticipantsIndexRoute: SupportParticipantsIndexRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AttendanceRoute: AttendanceRoute,
  CohortsRoute: CohortsRoute,
  FaithProjectsRoute: FaithProjectsRoute,
  LoginRoute: LoginRoute,
  ResourcesRoute: ResourcesRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRouteWithChildren,
  UsersRoute: UsersRoute,
  ParticipantsIdRoute: ParticipantsIdRoute,
  ParticipantsIndexRoute: ParticipantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
